### ISSUE TITLE
wrong allocated size

### ISSUE THREAD

**Issue by estarossa0** [StrixWL/Get_Next_Line#2]
https://github.com/StrixWL/Get_Next_Line/blob/6b1330024b598a4fca9d875c199ccdba2804f838/get_next_line.c#L12
if the line length is > BUFFERSIZE, this will cause buffer pointer to get over it's allocated memory size and will definitely cause the program to crash with asap with short BUFFERSIZR and long line length

**Comment by StrixWL** [comment]
naruhodoo
