### ISSUE TITLE
fun fact char do exist

### ISSUE THREAD

**Issue by estarossa0** [StrixWL/Get_Next_Line#3]
https://github.com/StrixWL/Get_Next_Line/blob/6b1330024b598a4fca9d875c199ccdba2804f838/get_next_line.c#L13
why would you make a `char *` and allocate 1 byte to it ever heard of `char` ?

**Comment by StrixWL** [comment]
HHHHH THIS IS THE MOST EMBARRASSING SHIT I HAVE EVER DONE IN MY LIFE
