### ISSUE TITLE
infinite loop if read failed

### ISSUE THREAD

**Issue by estarossa0** [StrixWL/Get_Next_Line#4]
if `read` failed and returned `-1` here
https://github.com/StrixWL/Get_Next_Line/blob/6b1330024b598a4fca9d875c199ccdba2804f838/get_next_line.c#L20

this will cause this condition to be true (k) and read will keep returning `-1` and not changing `temp` value causing the program to fall in an infinite loop
https://github.com/StrixWL/Get_Next_Line/blob/6b1330024b598a4fca9d875c199ccdba2804f838/get_next_line.c#L18

**Comment by StrixWL** [comment]
yeah i didnt think of that case
